"""Template Description

Revision ID: 5eaabc2985bc
Revises: d8ad40bec2f6
Create Date: 2026-04-07 22:45:06.228447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eaabc2985bc'
down_revision: Union[str, None] = 'd8ad40bec2f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('description', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'description')
    # ### end Alembic commands ###
