"""Add new columns

Revision ID: 8d8a64d6196a
Revises: 
Create Date: 2026-04-05 17:18:00.696034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d8a64d6196a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('country', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('gender', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_column('users', 'country')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
